import { cn } from "@/lib/utils";
import { Sparkles, Calculator } from "lucide-react";
import { Skeleton } from "@/components/ui/skeleton";

interface AIInsightPanelProps {
  title: string;
  body: string;
  timestamp?: string;
  className?: string;
  footer?: React.ReactNode;
  /**
   * "ai" — content was generated by an LLM (e.g. market-brief edge function).
   *        Renders the "Max's Read" eyebrow with a sparkle and AI badge.
   * "computed" — content is a deterministic regime/indicator summary.
   *        Renders a "Computed Read" eyebrow with a calculator glyph so the
   *        operator can tell at a glance it's not a model output.
   * Defaults to "ai" for backwards compatibility with existing callers.
   */
  kind?: "ai" | "computed";
  /** When true, render skeleton placeholders instead of the body text. */
  loading?: boolean;
}

export function AIInsightPanel({
  title,
  body,
  timestamp,
  className,
  footer,
  kind = "ai",
  loading,
}: AIInsightPanelProps) {
  const isAi = kind === "ai";
  return (
    <div
      className={cn(
        "panel p-4 relative overflow-hidden",
        isAi &&
          "before:absolute before:inset-0 before:bg-gradient-to-br before:from-primary/5 before:to-transparent before:pointer-events-none",
        className,
      )}
    >
      <div className="relative">
        <div className="flex items-center justify-between mb-2">
          <div className="flex items-center gap-2">
            <span
              className={cn(
                "h-6 w-6 rounded-md flex items-center justify-center",
                isAi ? "bg-primary/15 text-primary" : "bg-muted text-muted-foreground",
              )}
            >
              {isAi ? <Sparkles className="h-3.5 w-3.5" /> : <Calculator className="h-3.5 w-3.5" />}
            </span>
            <span
              className={cn(
                "text-[11px] uppercase tracking-wider font-medium",
                isAi ? "text-primary/90" : "text-muted-foreground",
              )}
            >
              {isAi ? "Max's Read" : "Computed Read"}
            </span>
            {isAi && (
              <span className="text-[9px] uppercase tracking-wider font-semibold px-1.5 py-0.5 rounded bg-primary/15 text-primary">
                AI
              </span>
            )}
          </div>
          {timestamp && (
            <span className="text-[10px] uppercase tracking-wider text-muted-foreground tabular">{timestamp}</span>
          )}
        </div>
        <p className="text-sm font-medium text-foreground">{title}</p>
        <p className="text-sm text-muted-foreground mt-1.5 leading-relaxed">{body}</p>
        {footer && <div className="mt-3 pt-3 border-t border-border">{footer}</div>}
      </div>
    </div>
  );
}
