import { useEffect, useState } from "react";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { StatusBadge } from "@/components/trader/StatusBadge";
import { Brain, RefreshCw, Sparkles } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import ReactMarkdown from "react-markdown";
import type { TradeSignal } from "@/lib/domain-types";

interface SignalExplainDialogProps {
  signal: TradeSignal | null;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function SignalExplainDialog({ signal, open, onOpenChange }: SignalExplainDialogProps) {
  const [explanation, setExplanation] = useState<string>("");
  const [loading, setLoading] = useState(false);
  const [cached, setCached] = useState(false);

  const fetchExplanation = async (force = false) => {
    if (!signal) return;
    setLoading(true);
    try {
      const { data: sess } = await supabase.auth.getSession();
      const token = sess.session?.access_token;
      if (!token) {
        toast.error("Sign in first.");
        return;
      }
      const res = await fetch(`${import.meta.env.VITE_SUPABASE_URL}/functions/v1/signal-explain`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
          apikey: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY,
        },
        body: JSON.stringify({ signalId: signal.id, force }),
      });
      const json = await res.json();
      if (!res.ok) {
        if (res.status === 429) toast.error("Rate limited. Give it a sec.");
        else if (res.status === 402) toast.error("AI credits depleted.");
        else toast.error(json.error ?? "Explain failed");
        return;
      }
      setExplanation(json.explanation);
      setCached(!!json.cached);
    } catch {
      toast.error("Connection error.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (open && signal) {
      setExplanation("");
      setCached(false);
      fetchExplanation(false);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, signal?.id]);

  if (!signal) return null;

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <span className="h-7 w-7 rounded-md bg-primary/15 text-primary flex items-center justify-center">
              <Brain className="h-3.5 w-3.5" />
            </span>
            Deep-dive · {signal.side.toUpperCase()} {signal.symbol}
          </DialogTitle>
          <DialogDescription className="flex items-center gap-2 flex-wrap">
            <StatusBadge tone={signal.side === "long" ? "safe" : "blocked"} size="sm" dot>
              {signal.side}
            </StatusBadge>
            <span className="text-xs">@ ${signal.proposedEntry.toFixed(2)}</span>
            <span className="text-xs">·</span>
            <span className="text-xs">{(signal.confidence * 100).toFixed(0)}% confidence</span>
            <span className="text-xs">·</span>
            <span className="text-xs capitalize">{signal.regime.replace("_", " ")} regime</span>
            {cached && (
              <StatusBadge tone="neutral" size="sm">
                cached
              </StatusBadge>
            )}
          </DialogDescription>
        </DialogHeader>

        <div className="min-h-[200px]">
          {loading && !explanation ? (
            <div className="flex items-center justify-center py-12 text-muted-foreground text-sm">
              <Sparkles className="h-4 w-4 mr-2 animate-pulse" />
              The AI is thinking out loud…
            </div>
          ) : (
            <div className="prose prose-sm prose-invert max-w-none prose-p:my-2 prose-headings:text-foreground prose-headings:mt-4 prose-headings:mb-1 prose-strong:text-primary">
              <ReactMarkdown>{explanation || "_No explanation yet._"}</ReactMarkdown>
            </div>
          )}
        </div>

        <div className="flex items-center justify-between pt-3 border-t border-border">
          <p className="text-[10px] text-muted-foreground">
            Generated by {signal.aiModel || "AI"} · cached after first run
          </p>
          <Button
            size="sm"
            variant="outline"
            onClick={() => fetchExplanation(true)}
            disabled={loading}
            className="gap-1.5"
          >
            <RefreshCw className={`h-3.5 w-3.5 ${loading ? "animate-spin" : ""}`} />
            {loading ? "Re-thinking…" : "Regenerate"}
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
